import type { AdData } from '@/shared/types/ad';

export const mockData: AdData[] = [
  {
    id: 1,
    creative_name:
      'Adidas Running Launch Adidas Running Launch Adidas Running Launch Adidas Running Launch Adidas Running Launch',
    client: 'Adidas',
    delivery_types: 'Non-Trafficked',
    formats: ['300x250', '970x250'],
    features: ['Dynamic', 'Carousel'],
    zip_path: 'zips/Test.zip',
    thumbnail_path: 'previews/preview1.png',
    created_at: '2026-07-15T10:30:00Z',
  },
  {
    id: 2,
    creative_name: 'Always On High Speed',
    client: 'Virgin Media',
    delivery_types: 'Non-Trafficked',
    formats: ['300x250'],
    features: ['Dynamic', 'Countdown'],
    zip_path: 'zips/Test.zip',
    thumbnail_path: 'previews/preview2.png',
    created_at: '2026-07-15T10:29:00Z',
  },
  {
    id: 3,
    creative_name: 'Summer Blockbuster Launch',
    client: 'Disney+',
    delivery_types: 'In-Banner',
    formats: ['300x600', '970x250'],
    features: ['Dynamic', 'Video'],
    zip_path: 'zips/Test.zip',
    thumbnail_path: 'previews/preview3.png',
    created_at: '2026-07-15T10:28:00Z',
  },
  {
    id: 4,
    creative_name: 'Netflix Originals Reveal',
    client: 'Netflix',
    delivery_types: 'Social',
    formats: ['970x250'],
    features: ['Dynamic', 'Parallax'],
    zip_path: 'zips/Test.zip',
    thumbnail_path: 'previews/preview4.png',
    created_at: '2026-07-15T10:27:00Z',
  },
  {
    id: 5,
    creative_name: 'Luctus lao',
    client: 'Disney+',
    delivery_types: 'VPaid',
    formats: ['728x90'],
    features: ['Dynamic'],
    zip_path: 'zips/Test.zip',
    thumbnail_path: 'previews/preview1.png',
    created_at: '2026-06-18T11:00:00Z',
  },
  {
    id: 6,
    creative_name: 'Neque lorem',
    client: 'Virgin Media',
    delivery_types: 'Non-Trafficked',
    formats: ['970x250'],
    features: ['Dynamic'],
    zip_path: 'zips/Test.zip',
    thumbnail_path: 'previews/preview2.png',
    created_at: '2026-06-22T08:30:00Z',
  },
  {
    id: 7,
    creative_name: 'Lorem ipsum dolor sit amet',
    client: 'Netflix',
    delivery_types: 'Pre-rendered',
    formats: ['300x250'],
    features: ['Dynamic'],
    zip_path: 'zips/Test.zip',
    thumbnail_path: 'previews/preview3.png',
    created_at: '2026-06-12T13:45:00Z',
  },
  {
    id: 8,
    creative_name: 'Quisque ad v',
    client: 'Amazon',
    delivery_types: 'Non-Trafficked',
    formats: ['320x50'],
    features: ['Dynamic'],
    zip_path: 'zips/Test.zip',
    thumbnail_path: 'previews/preview4.png',
    created_at: '2026-06-28T17:10:00Z',
  },
  {
    id: 9,
    creative_name: 'Cras per e',
    client: 'Deliveroo',
    delivery_types: 'Non-Trafficked',
    formats: ['1200x1200'],
    features: ['Dynamic'],
    zip_path: 'zips/Test.zip',
    thumbnail_path: 'previews/preview1.png',
    created_at: '2026-06-14T12:00:00Z',
  },
  {
    id: 10,
    creative_name: 'In mattis cla',
    client: 'Amazon India',
    delivery_types: 'In-Banner',
    formats: ['300x250'],
    features: ['Dynamic'],
    zip_path: 'zips/Test.zip',
    thumbnail_path: 'previews/preview2.png',
    created_at: '2026-06-30T19:30:00Z',
  },
];
